# Generated by Django 4.2.25 on 2025-10-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='اسم المقرر')),
                ('course_number', models.IntegerField(help_text='Course Number represents the Course ID.', verbose_name='رمز المقرر')),
            ],
        ),
    ]
